
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: test-app
        image: https://harbor-cicsk8s.hursley.ibm.comockerhub/library/httpd:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 50Mi